{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flash.serviceAccountName" . }}
  labels:
    {{- include "flash.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}

